# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.3 on 2026-04-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TranslationLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_draft_id", models.IntegerField(db_index=True)),
                ("translated_draft_id", models.IntegerField(unique=True)),
                ("source_language", models.CharField(max_length=5)),
                ("target_language", models.CharField(max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "contentdb_translator_link",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_draft_id", "target_language"), name="unique_source_target_lang"
                    )
                ],
            },
        ),
    ]
