# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.7 on 2026-07-11 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_contentdb_translator", "0001_add_translation_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslateWizardProxy",
            fields=[],
            options={
                "verbose_name": "Translate content",
                "verbose_name_plural": "Translate content",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("django_contentdb_translator.translationlink",),
        ),
    ]
